---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq-from-planner-server
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: planner
    - podSelector:
        matchLabels:
          app: server
    ports:
    - port: 5672
      protocol: TCP
