---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topo-to-mongodb
spec:
  podSelector:
    matchLabels:
      app: toposervice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mongodb
    ports:
    - port: 27017
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topo-from-planner-ingress
spec:
  podSelector:
    matchLabels:
      app: toposervice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: planner
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
