---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
        dns-policy: {{ .Release.Name }}-enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-server
        image: {{ .Values.server.image.name }}:{{ .Values.server.image.version }}
        command: ["bash"]
        args:
        - "-c"
        - "./wait-for-it.sh {{ .Release.Name }}-mysql-service:3306 -t 500 -- ./wait-for-it.sh {{ .Release.Name }}-rabbitmq-service:5672 -t 500 -- node src/server.js"
        ports:
        - containerPort: 3000
        env:
        {{- range $.Values.server.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: MYSQL_HOST
          value: {{ .Release.Name }}-mysql-service
        - name: RABBITMQ_URL
          value: "amqp://root:password@{{ .Release.Name }}-rabbitmq-service" 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
  labels:
    app: {{ .Release.Name }}-server
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: {{ .Values.ports.serverPort }}
  selector:
    app: {{ .Release.Name }}-server
  type: {{ .Values.app.ingress | ternary "ClusterIP" .Values.app.serverTypeWithoutIngress }}
