{{- if .Values.app.withNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-weather-from-planner
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-weatherservice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-planner
    ports:
    - port: 9090
      protocol: TCP
{{- end }}