{{- if .Values.app.withNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-to-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-mongodb
    ports:
    - port: 27017
      protocol: TCP

{{- if .Values.app.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-topo-from-planner-ingress
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-planner
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
{{- else }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-toposervice-from-network
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-toposervice
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
{{- end }}
{{- end }}