---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  {{- if .Values.app.withVolumes }}
  storageClassName: {{ .Values.mysql.volumes.name }}
  {{- end}}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi