{{- if .Values.app.withNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mysql-from-server
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-server
    ports:
    - port: 3306
      protocol: TCP
{{- end }}