app:
  ingress: true
  serverTypeWithoutIngress: Nodeport
  domain: cluster-ip
  withVolumes: true
  withNetworkPolicies: true

nameOverride: "Eolo"
fullnameOverride: "Eoloplanner"

ports:
  topoPort: "topo-port"
  serverPort: "server-port"
  weatherPort: "weather-port"
  mysqlPort: "mysql-port"
  rabbitmqPort: "rabbitmq-port"


mongo:
  image:
    name: mongo
    version: 4.2.12-bionic
  volumes:
    name: "mongo"
    hostPath: "/db/mongo"
    storage: 1Gi
  envVars:
    - key: MONGO_INITDB_DATABASE
      value: topoDB
    - key: MONGO_INITDB_ROOT_USERNAME
      value: root
    - key: MONGO_INITDB_ROOT_PASSWORD
      value: password

server:
  image: 
    name: oscarsotosanchez/server
    version: v1.0
  envVars:
    - name: MYSQL_HOST
      value: mysql-service
    - name: MYSQL_DB
      value: eoloplantsDB
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASS
      value: password
    - name: RABBITMQ_URL
      value: amqp://root:password@rabbitmq-service

mysql:
  image:
    name: mysql
    version: 8.0.22
  volumes:
    name: "mysql"
    hostPath: "/db/mysql"
    storage: 1Gi
  envVars:
    - name: MYSQL_ROOT_PASSWORD
      value: password # TODO: THIS SHOULD BE RANDOM
    - name: MYSQL_DATABASE
      value: eoloplantsDB

rabbitmq:
  image:
    name: "rabbitmq"
    value: "3-management"
  volumes:
    name: "rabbitmq"
    hostPath: "/db/rabbitmq"
    storage: 1Gi
  envVars:
    - name: RABBITMQ_DEFAULT_USER
      value: root
    - name: RABBITMQ_DEFAULT_PASS
      value: password # TODO: THIS SHOULD BE RANDOM

planner:
  image:
    name: "javiergarciagon/eoloplanner-planner-modified"
    version: "v.2.0.0"
  envVars:
    - name: TOPO_HOST
      value: toposervice-service
    - name: TOPO_PORT
      value: "8080"
    - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
      value: static://weatherservice-service:9090
    - name: SPRING_RABBITMQ_HOST
      value: rabbitmq-service
    - name: SPRING_RABBITMQ_PORT
      value: "5672"
    - name: SPRING_RABBITMQ_USERNAME
      value: root
    - name: SPRING_RABBITMQ_PASSWORD
      value: password

topo:
  image:
    name: "oscarsotosanchez/toposervice"
    version: "v1.0"
  envVars: