{{- if .Values.app.withNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-to-rabbit-weather-topo
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-rabbitmq
    ports:
    - port: 5672
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-weatherservice
    ports:
    - port: 9090
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-toposervice
    ports:
    - port: 8080
      protocol: TCP
{{- end }}