---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-planner
        dns-policy: {{ .Release.Name }}-enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-planner
        image: {{ .Values.planner.image.name }}:{{ .Values.planner.image.version }}
        env:
        - name: TOPO_HOST
          value: {{ .Release.Name }}-toposervice-service
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://{{ .Release.Name }}-weatherservice-service:9090
        - name: SPRING_RABBITMQ_HOST
          value: {{ .Release.Name }}-rabbitmq-service
        {{- range $.Values.planner.envVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
