---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rabbitmq-pvc
spec:
  {{- if .Values.app.withVolumes }}
  storageClassName: {{ .Values.rabbitmq.volumes.name }}
  {{- end}}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.volumes.storage }}