apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-rabbitmq-pv
spec:
  {{- if .Values.app.withVolumes }}
  storageClassName: {{ .Values.rabbitmq.volumes.name }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.rabbitmq.volumes.storage }}
  hostPath:
    path: {{ .Values.rabbitmq.volumes.hostPath }}