{{- if .Values.app.withNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-mongodb-from-topo
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-toposervice
    ports:
    - port: 27017
      protocol: TCP
{{- end }}